USE prode;

-- FASES
INSERT INTO fases (nombre) VALUES
('Grupos'),
('Dieciseisavos'),
('Octavos'),
('Cuartos'),
('Semifinal'),
('Tercer Puesto'),
('Final');

-- Clasificados

INSERT INTO clasificados (grupo, pais_clasificado)
VALUES
('A', 'Mexico'),
('A', 'Sudafrica'),
('A', 'Corea del Sur'),
('A', 'Republica Checa'),
('B', 'Canada'),
('B', 'Bosnia Herzegovina'),
('B', 'Suiza'),
('B', 'Qatar'),
('C', 'Brasil'),
('C', 'Marruecos'),
('C', 'Haiti'),
('C', 'Escocia'),
('D', 'Estados Unidos'),
('D', 'Paraguay'),
('D', 'Australia'),
('D', 'Turquia'),
('E', 'Alemania'),
('E', 'Curazao'),
('E', 'Costa de Marfil'),
('E', 'Ecuador'),
('F', 'Paises Bajos'),
('F', 'Japon'),
('F', 'Suecia'),
('F', 'Tunez'),
('G', 'Belgica'),
('G', 'Egipto'),
('G', 'Iran'),
('G', 'Nueva Zelanda'),
('H', 'Espana'),
('H', 'Cabo Verde'),
('H', 'Arabia Saudita'),
('H', 'Uruguay'),
('I', 'Francia'),
('I', 'Senegal'),
('I', 'Irak'),
('I', 'Noruega'),
('J', 'Argentina'),
('J', 'Argelia'),
('J', 'Austria'),
('J', 'Jordania'),
('K', 'Portugal'),
('K', 'RD Congo'),
('K', 'Uzbekistan'),
('K', 'Colombia'),
('L', 'Inglaterra'),
('L', 'Croacia'),
('L', 'Ghana'),
('L', 'Panama');